# Generated by Django 4.1.3 on 2022-12-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0005_alter_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='contact1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='contact2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
